### ISSUE TITLE
Error message due to NamedTempoaryFile

### ISSUE THREAD

**Issue by MMIX2009** [dataprofessor/builder#1]
There seems to be an issue with the NamedTemporaryFile  in line 42.
Is it defined anywhere?

![NamedTemporaryFile_issue](https://github.com/dataprofessor/builder/assets/4305575/5701be41-3b0d-48d0-955a-66bca223cd13)

**Comment by dataprofessor** [comment]
The `streamlit_app.py` file has been corrected.

Please add the following at the top near the import statements:
```
from tempfile import NamedTemporaryFile
```

**Comment by MMIX2009** [comment]
> The `streamlit_app.py` file has been corrected.
> 
> Please add the following at the top near the import statements:
> 
> ```
> from tempfile import NamedTemporaryFile
> ```
Thank you that fixed the issue.
